export GOOGLE_APPLICATION_CREDENTIALS="CHANGE_THIS"
export CRUN_GENAI_SERVICE_SA="CHANGE_THIS"
export CRUN_GENAI_SERVICE_URL="CHANGE_THIS"
export PROJECT_ID="CHANGE_THIS"
export SEARCH_ENGINE_ID="CHANGE_THIS"
python app.py